### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by jugendhacker** [mip-tv/chrome-extension#1]
How can I install it in my Browser?

**Comment by mgjm** [comment]
Currently you need to clone the repository and modify the hardcoded url... replace `https://mip-tv.mgjm.de` with your own server (e.g. `http://localhost:8080`). Just use the search tool of your editor and you should find four matches.

After this change you can go to **[chrome://extensions/](chrome://extensions/)** and check the box for **Developer Mode**. Then the **Load unpacked extension** button will appear and you can select the folder of the repository to load the extension.

(Auf Deutsch heißt die Checkbox übrigens "Entwicklermodus" und dann auf "Entpackte Erweiterung laden")

**Comment by jugendhacker** [comment]
Wird es ein offiziellen Server von euch geben?

**Comment by mgjm** [comment]
Vermutlich eher nicht... da die Trennung von Nutzeraccounts noch nicht komplett umgesetzt ist. Die Idee ist es eigentlich die Chrome Extension ohne Server lauffähig zu machen. Wir hatten die Größe der GeoIP Datenbank falsch in Erinnerung gehabt... daher sollte es eigentlich auch komplett Clientseitig möglich sein.
[mmdb-reader](https://www.npmjs.com/package/mmdb-reader) sollte mit Webpack auch auf dem Client laufen.

**Comment by jugendhacker** [comment]
Ok
